"""Asserts this implementation satisfies its own exported cross-language
test vectors (spec/vectors/, generated by spec/export_vectors.py).

Why this test exists, given the same behaviour is already covered by the
hand-computed unit tests: the vectors are the contract a port in another
language is held to (see docs-internal/APP_ARCHITECTURE.md). If the Python
implementation changes and the vectors aren't regenerated, the contract
silently describes something nobody implements any more — and a Dart port
passing "the vectors" would be agreeing with a version of Python that no
longer exists. This test makes that rot impossible: change the behaviour
without regenerating, and it goes red here first.

The layering is deliberate:
  - test_scoring/test_extract/test_aqi/test_dates assert Python is RIGHT
    (hand-computed expectations)
  - this file asserts the exported vectors still MATCH Python
  - a port asserts it matches the same vectors
"""

from __future__ import annotations

import json
import re
from dataclasses import asdict
from datetime import date, datetime, timezone
from pathlib import Path

import pytest

from openlocalweather.aqi import hours_old, is_stale, summarize_ground_aqi
from openlocalweather.dates import add_days, prediction_row_date_for_target
from openlocalweather.extract import (
    extract_day0_predictions_from_hourly,
    extract_day_n_predictions_from_daily,
)
from openlocalweather.fetch.open_meteo import bucket_hourly_by_date, get_onset_hour
from openlocalweather.models import DailyActual, GroundAQIReading, ModelPrediction
from openlocalweather.comparison import compute_day_over_day
from openlocalweather.daypart import (
    daypart_without_sun,
    forward_hours,
    reconcile_now,
    summarize_daypart,
)
from openlocalweather.config import LocationConfig, Point, SecondaryPoint
from openlocalweather.llm.prompt import build_system_prompt, build_user_prompt
from openlocalweather.llm.schema import (
    GeminiForecastResponse,
    to_gemini_schema,
    to_strict_json_schema,
)
from openlocalweather.verify.scoring import compute_rain_pct_trend, mean, score_prediction

VECTORS_DIR = Path(__file__).resolve().parents[1] / "spec" / "vectors"


def load(name: str) -> dict:
    return json.loads((VECTORS_DIR / name).read_text())


def as_json(value):
    """Normalizes a Python result into the same plain-JSON shape the vector
    file stores, so comparisons are like-for-like."""
    if value is None:
        return None
    if hasattr(value, "model_dump"):
        return value.model_dump(mode="json")
    if hasattr(value, "__dataclass_fields__"):
        return asdict(value)
    if isinstance(value, (date, datetime)):
        return value.isoformat()
    if isinstance(value, list):
        return [as_json(v) for v in value]
    return value


def check(case: dict, actual) -> None:
    assert as_json(actual) == case["expected"], f"vector case failed: {case['name']}"


# ---------------------------------------------------------------------------
# dates
# ---------------------------------------------------------------------------


def test_vectors_prediction_row_date_for_target():
    data = load("dates.json")
    assert data["cases"], "vector file is empty"
    for case in data["cases"]:
        i = case["input"]
        check(case, prediction_row_date_for_target(date.fromisoformat(i["target_date"]), i["lead_time_days"]))


def test_vectors_add_days():
    for case in load("dates_add_days.json")["cases"]:
        i = case["input"]
        check(case, add_days(date.fromisoformat(i["date"]), i["days"]))


# ---------------------------------------------------------------------------
# scoring
# ---------------------------------------------------------------------------


def test_vectors_score_prediction():
    for case in load("scoring_score_prediction.json")["cases"]:
        i = case["input"]
        predicted = ModelPrediction.model_validate(i["predicted"]) if i["predicted"] is not None else None
        actual = DailyActual.model_validate(i["actual"]) if i["actual"] is not None else None
        check(case, score_prediction(predicted, actual, i["lead_time_days"]))


def test_vectors_mean():
    for case in load("scoring_mean.json")["cases"]:
        check(case, mean(case["input"]["values"]))


def test_vectors_rain_pct_trend():
    for case in load("scoring_rain_pct_trend.json")["cases"]:
        i = case["input"]
        label, delta = compute_rain_pct_trend(
            i["rolling_10_rain_pct"],
            i["rolling_30_rain_pct"],
            i["checks_in_window_10"],
            i["checks_in_window_30"],
            min_checks_short=i["min_checks_short"],
            min_checks_long=i["min_checks_long"],
            threshold_pct=i["threshold_pct"],
        )
        assert {"label": label, "delta": delta} == case["expected"], f"vector case failed: {case['name']}"


# ---------------------------------------------------------------------------
# extraction
# ---------------------------------------------------------------------------


def test_vectors_extract_day0():
    for case in load("extract_day0.json")["cases"]:
        i = case["input"]
        check(case, extract_day0_predictions_from_hourly(i["hourly_multi_model"], i["models"], i["threshold"]))


def test_vectors_extract_day_n():
    for case in load("extract_day_n.json")["cases"]:
        i = case["input"]
        check(
            case,
            extract_day_n_predictions_from_daily(i["daily_multi_model"], i["day_index"], i["models"], i["threshold"]),
        )


def test_vectors_onset_hour():
    for case in load("extract_onset_hour.json")["cases"]:
        i = case["input"]
        check(case, get_onset_hour(i["times"], i["precip"], i["threshold"]))


# ---------------------------------------------------------------------------
# ground AQI
# ---------------------------------------------------------------------------


def test_vectors_aqi_staleness():
    for case in load("aqi_staleness.json")["cases"]:
        i = case["input"]
        reading = GroundAQIReading.model_validate(i["reading"])
        now = datetime.fromisoformat(i["now"])
        got = {"hours_old": hours_old(reading, now), "is_stale": is_stale(reading, now)}
        assert got["is_stale"] == case["expected"]["is_stale"], f"vector case failed: {case['name']}"
        if case["expected"]["hours_old"] is None:
            assert got["hours_old"] is None, f"vector case failed: {case['name']}"
        else:
            assert got["hours_old"] == pytest.approx(case["expected"]["hours_old"]), f"vector case failed: {case['name']}"


def test_vectors_aqi_summary():
    for case in load("aqi_summary.json")["cases"]:
        i = case["input"]
        readings = [GroundAQIReading.model_validate(r) for r in i["readings"]]
        check(case, summarize_ground_aqi(readings, datetime.fromisoformat(i["now"])))


def test_vectors_bucket_hourly_by_date():
    for case in load("bucket_hourly_by_date.json")["cases"]:
        i = case["input"]
        result = bucket_hourly_by_date(i["hourly_json"], i["threshold"])
        got = {d.isoformat(): as_json(v) for d, v in result.items()}
        assert got == case["expected"], f"vector case failed: {case['name']}"


def test_vectors_verification():
    """The full verification pass, pinned. This is what turns "accurate" from
    a claim into a measurement, so the two implementations agreeing is not a
    nicety — an app whose accuracy screen disagreed with the site's would
    discredit both."""
    from openlocalweather.models import (
        DailyLogEntry,
        LogEntryMeta,
        ModelPredictionsByLead,
        TrackRecord,
        TrackRecordEntry,
    )
    from openlocalweather.verify.pipeline import (
        run_deterministic_verification_and_scoring,
    )

    for case in load("verification.json")["cases"]:
        i = case["input"]
        logs = {}
        for iso, by_lead in i["predictions"].items():
            d = date.fromisoformat(iso)
            logs[d] = DailyLogEntry(
                date=d, rain_expected="x", temp_high_c=26.0, temp_low_c=18.0,
                temp_high_low_display="26/18", mslp_trend_24h="", synoptic_pattern="",
                narrative_markdown="n",
                model_predictions=ModelPredictionsByLead(
                    day0=[ModelPrediction(**p) for p in by_lead.get("0", [])]
                ),
                meta=LogEntryMeta(
                    generated_at_utc=datetime(2026, 8, 21, tzinfo=timezone.utc),
                    llm_provider="t", llm_model="t", pipeline_version="0",
                ),
            )
        actuals = {
            date.fromisoformat(iso): DailyActual(**a) for iso, a in i["actuals"].items()
        }
        prior = [
            TrackRecordEntry(
                model=e["model"], lead_time_days=e["lead_time_days"],
                all_time_checks=e["all_time_checks"],
                all_time_correct=e["all_time_correct"],
                all_time_rain_pct=e["all_time_rain_pct"],
            )
            for e in i["prior_track_record"]
        ]
        result = run_deterministic_verification_and_scoring(
            log_lookup=lambda d: logs.get(d),
            prior_track_record=TrackRecord(
                generated_at_utc=datetime(2026, 8, 21, tzinfo=timezone.utc),
                entries=prior,
            ),
            actuals_primary=actuals,
            today=date.fromisoformat(i["today"]),
            yesterday=date.fromisoformat(i["yesterday"]),
            models=i["models"],
            lead_times_days=i["lead_times_days"],
            earliest_log_date=date.fromisoformat(i["earliest_record_date"]),
        )
        want = case["expected"]
        name = case["name"]

        for got, w in zip(result.lead_time_results, want["lead_time_results"]):
            assert got.lead_time_days == w["lead_time_days"], name
            # Absent, not wrong: a model with no data must not appear here.
            assert sorted(got.per_model_scores) == w["scored_models"], name

        for got, w in zip(result.updated_track_record.entries, want["track_record"]):
            assert got.model == w["model"], name
            assert got.rolling_10_rain_pct == w["rolling_10_rain_pct"], name
            assert got.all_time_checks == w["all_time_checks"], name
            assert got.all_time_correct == w["all_time_correct"], name
            assert got.checks_in_window_10 == w["checks_in_window_10"], name


def test_vectors_spend():
    """Both surfaces must answer "is one more call allowed" identically. The
    boundary is the sensitive part: an inclusive cutoff, or a calendar day
    instead of a rolling window, permits real extra spending while looking
    correct in review."""
    from openlocalweather.spend import SpendRecord, calls_in_window, prune

    for case in load("spend.json")["cases"]:
        i = case["input"]
        now = datetime.fromisoformat(i["now"])
        records = [SpendRecord.from_json(r) for r in i["records"]]
        want = case["expected"]
        name = case["name"]

        assert calls_in_window(records, now) == want["calls_in_window"], name
        kept = [r.at.isoformat() for r in prune(records, now)]
        assert kept == [r["at"] for r in want["kept_after_prune"]], name


def test_vectors_coverage():
    """The three-way split is the contract. Treating a peer_gap as
    never_published would reproduce the months-long silence this module
    exists to end."""
    from openlocalweather.coverage import detect_coverage
    from openlocalweather.models import DailyLogEntry, LogEntryMeta, ModelPredictionsByLead

    for case in load("coverage.json")["cases"]:
        i = case["input"]
        logs = {}
        for iso, by_lead in i["predictions"].items():
            d = date.fromisoformat(iso)
            logs[d] = DailyLogEntry(
                date=d, rain_expected="x", temp_high_c=26.0, temp_low_c=18.0,
                temp_high_low_display="26/18", mslp_trend_24h="", synoptic_pattern="",
                narrative_markdown="n",
                model_predictions=ModelPredictionsByLead(
                    day0=[ModelPrediction(**p) for p in by_lead.get("0", [])]
                ),
                meta=LogEntryMeta(
                    generated_at_utc=datetime(2026, 8, 21, tzinfo=timezone.utc),
                    llm_provider="t", llm_model="t", pipeline_version="0",
                ),
            )
        got = detect_coverage(
            log_lookup=lambda d: logs.get(d),
            today=date.fromisoformat(i["today"]),
            models=i["models"],
            lead_times_days=i["lead_times_days"],
        )
        want = case["expected"]
        name = case["name"]
        assert len(got) == len(want), f"{name}: finding count"
        for g, w in zip(got, want):
            assert g.kind == w["kind"], name
            assert g.model == w["model"], name
            assert g.variable == w["variable"], name
            assert g.peers_with_value == w["peers_with_value"], name


def test_vectors_synoptic():
    """The bounded vocabulary is the contract — a direction, never a centre,
    a track, or a front. Statements are compared verbatim because they are
    published prose, not internal labels."""
    from openlocalweather.synoptic import summarize_synoptic

    for case in load("synoptic.json")["cases"]:
        got = summarize_synoptic(case["input"]["payload"])
        want = case["expected"]
        name = case["name"]
        if want is None:
            assert got is None, f"{name}: an absent picture must read as absent"
            continue
        assert got is not None, name
        assert got.lowest_label == want["lowest_label"], name
        assert got.highest_label == want["highest_label"], name
        assert got.gradient_hpa == want["gradient_hpa"], name
        assert got.gradient_strength == want["gradient_strength"], name
        assert got.tendencies == want["tendencies"], name
        assert got.statements == want["statements"], name


def test_vectors_weekly_review():
    """Both surfaces must publish the same claims from the same record.

    The gates are the sensitive part: an implementation that ranked models one
    check earlier than the other would state a conclusion the other withholds,
    and a user comparing the app against the site would have no way to tell
    which was right.
    """
    from openlocalweather.models import DailyLogEntry, LogEntryMeta, ModelPredictionsByLead
    from openlocalweather.review import build_weekly_review

    for case in load("weekly_review.json")["cases"]:
        i = case["input"]
        logs = {}
        for iso, by_lead in i["predictions"].items():
            d = date.fromisoformat(iso)
            logs[d] = DailyLogEntry(
                date=d, rain_expected="x", temp_high_c=26.0, temp_low_c=18.0,
                temp_high_low_display="26/18", mslp_trend_24h="", synoptic_pattern="",
                narrative_markdown="n",
                model_predictions=ModelPredictionsByLead(
                    day0=[ModelPrediction(**p) for p in by_lead.get("0", [])]
                ),
                meta=LogEntryMeta(
                    generated_at_utc=datetime(2026, 8, 21, tzinfo=timezone.utc),
                    llm_provider="t", llm_model="t", pipeline_version="0",
                ),
            )
        actuals = {
            date.fromisoformat(iso): DailyActual(**a) for iso, a in i["actuals"].items()
        }
        review = build_weekly_review(
            log_lookup=lambda d: logs.get(d),
            actuals=actuals,
            all_log_dates=sorted(logs),
            today=date.fromisoformat(i["today"]),
            models=i["models"],
            lead_times_days=i["lead_times_days"],
        )
        expected = case["expected"]
        name = case["name"]
        assert review.data_sufficiency == expected["data_sufficiency"], name
        assert len(review.findings) == len(expected["findings"]), (
            f"{name}: finding COUNT must match — an extra or missing finding is "
            "a different published claim"
        )
        for got, want in zip(review.findings, expected["findings"]):
            assert got.kind == want["kind"], name
            assert got.claim == want["claim"], name
            assert got.evidence == want["evidence"], name
            assert got.confidence == want["confidence"], name


def test_vectors_user_prompt():
    """The per-run message, pinned verbatim.

    The cold-start case carries the weight: every "Unavailable — ..." string
    is what stops a missing input reading as a measurement, and it is also
    exactly the shape of a new user's very first forecast.
    """
    for case in load("llm_user_prompt.json")["cases"]:
        i = dict(case["input"])
        got = build_user_prompt(
            today=date.fromisoformat(i.pop("today")),
            yesterday=date.fromisoformat(i.pop("yesterday")),
            **i,
        )
        assert got == case["expected"], f"vector case failed: {case['name']}"


def test_vectors_llm_schemas():
    """Guards the structured-output contract sent to real provider APIs."""
    for case in load("llm_schema_gemini.json")["cases"]:
        assert to_gemini_schema(GeminiForecastResponse) == case["expected"]
    for case in load("llm_schema_strict.json")["cases"]:
        assert to_strict_json_schema(GeminiForecastResponse) == case["expected"]


def test_vectors_system_prompt():
    """The instruction set behind every forecast — pinned verbatim so a port
    cannot quietly reason from different instructions."""
    for case in load("llm_system_prompt.json")["cases"]:
        i = case["input"]
        loc = i["location"]
        sec = loc["secondary_point"]
        location = LocationConfig(
            region_name=loc["region_name"],
            primary_place_name=loc["primary_place_name"],
            timezone="UTC",
            primary_point=Point(lat=0.0, lon=0.0),
            secondary_point=SecondaryPoint(
                enabled=sec["enabled"], name=sec["name"], section_label=sec["section_label"]
            ),
        )
        got = build_system_prompt(
            location,
            historical_lookback_days=i["historical_lookback_days"],
            rolling_window_short=i["rolling_window_short"],
            rolling_window_long=i["rolling_window_long"],
            is_reissue=i["is_reissue"],
        )
        assert got == case["expected"], f"vector case failed: {case['name']}"


def test_vectors_day_over_day():
    """The Overview's opening sentence — the one a live run got wrong."""
    for case in load("day_over_day.json")["cases"]:
        i = case["input"]
        y = DailyActual.model_validate(i["yesterday_actual"]) if i["yesterday_actual"] else None
        preds = [ModelPrediction.model_validate(p) for p in i["today_day0_predictions"]]
        assert as_json(compute_day_over_day(y, preds)) == case["expected"], (
            f"vector case failed: {case['name']}"
        )


# ---------------------------------------------------------------------------
# Meta
# ---------------------------------------------------------------------------


def test_every_vector_file_is_exercised():
    """A vector file with no test is a contract nobody checks. Adding one
    without wiring it up here should fail loudly rather than pass quietly."""
    covered = {
        "dates.json",
        "dates_add_days.json",
        "scoring_score_prediction.json",
        "scoring_mean.json",
        "scoring_rain_pct_trend.json",
        "extract_day0.json",
        "extract_day_n.json",
        "extract_onset_hour.json",
        "aqi_staleness.json",
        "aqi_summary.json",
        "bucket_hourly_by_date.json",
        "llm_schema_gemini.json",
        "llm_schema_strict.json",
        "llm_system_prompt.json",
        "llm_user_prompt.json",
        "weekly_review.json",
        "synoptic.json",
        "coverage.json",
        "spend.json",
        "verification.json",
        "day_over_day.json",
        "daypart.json",
        "daypart_without_sun.json",
        "daypart_clock.json",
        "daypart_forward_hours.json",
    }
    on_disk = {p.name for p in VECTORS_DIR.glob("*.json")}
    assert on_disk == covered, (
        f"vector files not exercised by a test: {sorted(on_disk - covered)}; "
        f"tests referencing missing files: {sorted(covered - on_disk)}"
    )


def test_vector_files_declare_a_known_format_version():
    for path in VECTORS_DIR.glob("*.json"):
        data = json.loads(path.read_text())
        assert data.get("vector_format_version") == 1, f"{path.name} has an unexpected format version"
        assert data.get("function"), f"{path.name} is missing its function name"
        assert data.get("cases"), f"{path.name} has no cases"


def test_readme_coverage_table_lists_every_vector():
    """Documentation that silently goes stale is worse than none — it reads
    as authoritative. The coverage table predated seven vector files before
    this guard existed."""
    readme = (VECTORS_DIR.parent / "README.md").read_text()
    documented = set(re.findall(r"^\| `([\w.]+\.json)` \|", readme, re.M))
    on_disk = {p.name for p in VECTORS_DIR.glob("*.json")}
    assert documented == on_disk, (
        f"undocumented vectors: {sorted(on_disk - documented)}; "
        f"documented but missing: {sorted(documented - on_disk)}"
    )


def test_vectors_daypart():
    for c in load("daypart.json")["cases"]:
        i = c["input"]
        nxt = i.get("next_sunrise")
        got = summarize_daypart(
            datetime.fromisoformat(i["now"]),
            datetime.fromisoformat(i["sunrise"]),
            datetime.fromisoformat(i["sunset"]),
            datetime.fromisoformat(nxt) if nxt else None,
        )
        check(c, got.to_json())


def test_vectors_daypart_without_sun():
    for c in load("daypart_without_sun.json")["cases"]:
        got = daypart_without_sun(datetime.fromisoformat(c["input"]["now"]))
        check(c, got.to_json())


def test_vectors_daypart_clock():
    for c in load("daypart_clock.json")["cases"]:
        i = c["input"]
        now, warning = reconcile_now(
            datetime.fromisoformat(i["system_local"]),
            i["server_date_header"],
            i["utc_offset_seconds"],
        )
        check(c, {"now": now.isoformat(), "warned": warning is not None})


def test_vectors_daypart_forward_hours():
    for c in load("daypart_forward_hours.json")["cases"]:
        i = c["input"]
        got = forward_hours(i["hourly_multi_model"], datetime.fromisoformat(i["now"]))
        check(c, got)
