"""Asserts this implementation satisfies its own exported cross-language
test vectors (spec/vectors/, generated by spec/export_vectors.py).

Why this test exists, given the same behaviour is already covered by the
hand-computed unit tests: the vectors are the contract a port in another
language is held to (see docs-internal/APP_ARCHITECTURE.md). If the Python
implementation changes and the vectors aren't regenerated, the contract
silently describes something nobody implements any more — and a Dart port
passing "the vectors" would be agreeing with a version of Python that no
longer exists. This test makes that rot impossible: change the behaviour
without regenerating, and it goes red here first.

The layering is deliberate:
  - test_scoring/test_extract/test_aqi/test_dates assert Python is RIGHT
    (hand-computed expectations)
  - this file asserts the exported vectors still MATCH Python
  - a port asserts it matches the same vectors
"""

from __future__ import annotations

import json
from dataclasses import asdict
from datetime import date, datetime
from pathlib import Path

import pytest

from openlocalweather.aqi import hours_old, is_stale, summarize_ground_aqi
from openlocalweather.dates import add_days, prediction_row_date_for_target
from openlocalweather.extract import (
    extract_day0_predictions_from_hourly,
    extract_day_n_predictions_from_daily,
)
from openlocalweather.fetch.open_meteo import bucket_hourly_by_date, get_onset_hour
from openlocalweather.models import DailyActual, GroundAQIReading, ModelPrediction
from openlocalweather.config import LocationConfig, Point, SecondaryPoint
from openlocalweather.llm.prompt import build_system_prompt
from openlocalweather.llm.schema import (
    GeminiForecastResponse,
    to_gemini_schema,
    to_strict_json_schema,
)
from openlocalweather.verify.scoring import compute_rain_pct_trend, mean, score_prediction

VECTORS_DIR = Path(__file__).resolve().parents[1] / "spec" / "vectors"


def load(name: str) -> dict:
    return json.loads((VECTORS_DIR / name).read_text())


def as_json(value):
    """Normalizes a Python result into the same plain-JSON shape the vector
    file stores, so comparisons are like-for-like."""
    if value is None:
        return None
    if hasattr(value, "model_dump"):
        return value.model_dump(mode="json")
    if hasattr(value, "__dataclass_fields__"):
        return asdict(value)
    if isinstance(value, (date, datetime)):
        return value.isoformat()
    if isinstance(value, list):
        return [as_json(v) for v in value]
    return value


def check(case: dict, actual) -> None:
    assert as_json(actual) == case["expected"], f"vector case failed: {case['name']}"


# ---------------------------------------------------------------------------
# dates
# ---------------------------------------------------------------------------


def test_vectors_prediction_row_date_for_target():
    data = load("dates.json")
    assert data["cases"], "vector file is empty"
    for case in data["cases"]:
        i = case["input"]
        check(case, prediction_row_date_for_target(date.fromisoformat(i["target_date"]), i["lead_time_days"]))


def test_vectors_add_days():
    for case in load("dates_add_days.json")["cases"]:
        i = case["input"]
        check(case, add_days(date.fromisoformat(i["date"]), i["days"]))


# ---------------------------------------------------------------------------
# scoring
# ---------------------------------------------------------------------------


def test_vectors_score_prediction():
    for case in load("scoring_score_prediction.json")["cases"]:
        i = case["input"]
        predicted = ModelPrediction.model_validate(i["predicted"]) if i["predicted"] is not None else None
        actual = DailyActual.model_validate(i["actual"]) if i["actual"] is not None else None
        check(case, score_prediction(predicted, actual, i["lead_time_days"]))


def test_vectors_mean():
    for case in load("scoring_mean.json")["cases"]:
        check(case, mean(case["input"]["values"]))


def test_vectors_rain_pct_trend():
    for case in load("scoring_rain_pct_trend.json")["cases"]:
        i = case["input"]
        label, delta = compute_rain_pct_trend(
            i["rolling_10_rain_pct"],
            i["rolling_30_rain_pct"],
            i["checks_in_window_10"],
            i["checks_in_window_30"],
            min_checks_short=i["min_checks_short"],
            min_checks_long=i["min_checks_long"],
            threshold_pct=i["threshold_pct"],
        )
        assert {"label": label, "delta": delta} == case["expected"], f"vector case failed: {case['name']}"


# ---------------------------------------------------------------------------
# extraction
# ---------------------------------------------------------------------------


def test_vectors_extract_day0():
    for case in load("extract_day0.json")["cases"]:
        i = case["input"]
        check(case, extract_day0_predictions_from_hourly(i["hourly_multi_model"], i["models"], i["threshold"]))


def test_vectors_extract_day_n():
    for case in load("extract_day_n.json")["cases"]:
        i = case["input"]
        check(
            case,
            extract_day_n_predictions_from_daily(i["daily_multi_model"], i["day_index"], i["models"], i["threshold"]),
        )


def test_vectors_onset_hour():
    for case in load("extract_onset_hour.json")["cases"]:
        i = case["input"]
        check(case, get_onset_hour(i["times"], i["precip"], i["threshold"]))


# ---------------------------------------------------------------------------
# ground AQI
# ---------------------------------------------------------------------------


def test_vectors_aqi_staleness():
    for case in load("aqi_staleness.json")["cases"]:
        i = case["input"]
        reading = GroundAQIReading.model_validate(i["reading"])
        now = datetime.fromisoformat(i["now"])
        got = {"hours_old": hours_old(reading, now), "is_stale": is_stale(reading, now)}
        assert got["is_stale"] == case["expected"]["is_stale"], f"vector case failed: {case['name']}"
        if case["expected"]["hours_old"] is None:
            assert got["hours_old"] is None, f"vector case failed: {case['name']}"
        else:
            assert got["hours_old"] == pytest.approx(case["expected"]["hours_old"]), f"vector case failed: {case['name']}"


def test_vectors_aqi_summary():
    for case in load("aqi_summary.json")["cases"]:
        i = case["input"]
        readings = [GroundAQIReading.model_validate(r) for r in i["readings"]]
        check(case, summarize_ground_aqi(readings, datetime.fromisoformat(i["now"])))


def test_vectors_bucket_hourly_by_date():
    for case in load("bucket_hourly_by_date.json")["cases"]:
        i = case["input"]
        result = bucket_hourly_by_date(i["hourly_json"], i["threshold"])
        got = {d.isoformat(): as_json(v) for d, v in result.items()}
        assert got == case["expected"], f"vector case failed: {case['name']}"


def test_vectors_llm_schemas():
    """Guards the structured-output contract sent to real provider APIs."""
    for case in load("llm_schema_gemini.json")["cases"]:
        assert to_gemini_schema(GeminiForecastResponse) == case["expected"]
    for case in load("llm_schema_strict.json")["cases"]:
        assert to_strict_json_schema(GeminiForecastResponse) == case["expected"]


def test_vectors_system_prompt():
    """The instruction set behind every forecast — pinned verbatim so a port
    cannot quietly reason from different instructions."""
    for case in load("llm_system_prompt.json")["cases"]:
        i = case["input"]
        loc = i["location"]
        sec = loc["secondary_point"]
        location = LocationConfig(
            region_name=loc["region_name"],
            primary_place_name=loc["primary_place_name"],
            timezone="UTC",
            primary_point=Point(lat=0.0, lon=0.0),
            secondary_point=SecondaryPoint(
                enabled=sec["enabled"], name=sec["name"], section_label=sec["section_label"]
            ),
        )
        got = build_system_prompt(
            location,
            historical_lookback_days=i["historical_lookback_days"],
            rolling_window_short=i["rolling_window_short"],
            rolling_window_long=i["rolling_window_long"],
            is_refresh=i["is_refresh"],
        )
        assert got == case["expected"], f"vector case failed: {case['name']}"


# ---------------------------------------------------------------------------
# Meta
# ---------------------------------------------------------------------------


def test_every_vector_file_is_exercised():
    """A vector file with no test is a contract nobody checks. Adding one
    without wiring it up here should fail loudly rather than pass quietly."""
    covered = {
        "dates.json",
        "dates_add_days.json",
        "scoring_score_prediction.json",
        "scoring_mean.json",
        "scoring_rain_pct_trend.json",
        "extract_day0.json",
        "extract_day_n.json",
        "extract_onset_hour.json",
        "aqi_staleness.json",
        "aqi_summary.json",
        "bucket_hourly_by_date.json",
        "llm_schema_gemini.json",
        "llm_schema_strict.json",
        "llm_system_prompt.json",
    }
    on_disk = {p.name for p in VECTORS_DIR.glob("*.json")}
    assert on_disk == covered, (
        f"vector files not exercised by a test: {sorted(on_disk - covered)}; "
        f"tests referencing missing files: {sorted(covered - on_disk)}"
    )


def test_vector_files_declare_a_known_format_version():
    for path in VECTORS_DIR.glob("*.json"):
        data = json.loads(path.read_text())
        assert data.get("vector_format_version") == 1, f"{path.name} has an unexpected format version"
        assert data.get("function"), f"{path.name} is missing its function name"
        assert data.get("cases"), f"{path.name} has no cases"
