"""Writes the day entry's JSON Schema — ROADMAP item 156's write shape.

The OLW day entry, `data/log/<date>.json`, is the only interchange format:
what a deployment commits, what the mailer and the app's viewer read, and
what the shared store holds. The store's writers cannot import this
package — the app builds an entry in Dart and the store's endpoint runs
wherever it runs — so the shape they are held to is this file, generated
from `DailyLogEntry` and pinned by `tests/test_entry_schema.py` so the
model and the schema cannot drift apart unnoticed.

Regenerate after any change to the entry's models:

    python spec/export_entry_schema.py
"""

from __future__ import annotations

import json
from pathlib import Path

from openlocalweather.models import DailyLogEntry

OUT_PATH = Path(__file__).resolve().parent / "day_entry.schema.json"


def entry_schema_text() -> str:
    """The schema as committed: sorted keys, two-space indent, one newline."""
    schema = DailyLogEntry.model_json_schema()
    schema["$schema"] = "https://json-schema.org/draft/2020-12/schema"
    schema["$comment"] = (
        "Generated by spec/export_entry_schema.py from DailyLogEntry; do not "
        "edit by hand. ROADMAP item 156: the shape a shared-store writer is "
        "held to."
    )
    return json.dumps(schema, indent=2, sort_keys=True) + "\n"


def main() -> None:
    OUT_PATH.write_text(entry_schema_text())
    print(f"  spec/{OUT_PATH.name}: written")


if __name__ == "__main__":
    main()
